<a name='1'></a>
## 1 - System of Linear Equations and Corresponding `NumPy` Arrays

Matrices can be used to solve systems of equations. But first, you need to represent the system using matrices. Given the following system of linear equations:

$$\begin{cases} 
2x_1-x_2+x_3+x_4=6, \\ x_1+2x_2-x_3-x_4=3, \\ -x_1+2x_2+2x_3+2x_4=14, \\ x_1-x_2+2x_3+x_4=8, \end{cases}\tag{1}$$

you will construct matrix $A$, where each row represents one equation in the system and each column represents a variable $x_1$, $x_2$, $x_3$, $x_4$. The free coefficients from the right sides of the equations you will put into vector $b$.

In [1]:
import numpy as np

In [25]:
A = np.array([
    [2, -1, 1, 1],
    [1, 2, -1, -1],
    [-1, 2, 2, 2],
    [1, -1, 2, 1]
    ],dtype=np.dtype(float))

b = np.array([6,3,14,8],dtype=np.dtype(float))

print(A)
print(b)

[[ 2. -1.  1.  1.]
 [ 1.  2. -1. -1.]
 [-1.  2.  2.  2.]
 [ 1. -1.  2.  1.]]
[ 6.  3. 14.  8.]


<a name='2'></a>
## 2 - Solution for the System of Equations with `NumPy` Linear Algebra Package

A system of four linear equations with four unknown variables has a unique solution if and only if the determinant of the corresponding matrix of coefficients is not equal to zero. `NumPy` provides quick and reliable ways to calculate the determinant of a square matrix and also to solve the system of linear equations.

In [26]:
# Checing the delta for the matrix
det = np.linalg.det(A)
print('The determinat for the martix is {:.2f}'.format(det))
np.linalg.solve(A, b)

The determinat for the martix is -17.00


array([2., 3., 4., 1.])

<a name='3'></a>
## 3 - Elementary Operations and Row Reduction

Even though the contemporary packages allow to find the solution with one line of the code, performing required algebraic operations manually helps to build foundations which are necessary for deep understanding of the machine learning algorithms. 

Here you will solve the system of linear equations algebraically using row reduction. It involves combination of the equations using elementary operations, eliminaring as many variables as possible for each equation. There are three valid operations which can be performed to bring the system of equations to equivalent one (with the same solutions):

- Multiply any row by non-zero number
- Add two rows and exchange one of the original rows with the result of the addition
- Swap rows

In [120]:
A_new = np.hstack((A,b.reshape(4,1)))
print(A_new)

# exchange row_num of the matrix M with its multiple by row_num_multiple
# Note: for simplicity, you can drop check if  row_num_multiple has non-zero value, which makes the operation valid
def MultiplyByNonZero(A, row, scaler):
    A_copy = A.copy()
    A_copy[row] = A_copy[row] * scaler
    print(A_copy)
    return A_copy

# R1 * 1/2
A_new = MultiplyByNonZero(A_new, 0 , 1/2)


# multiply row_num_1 by row_num_1_multiple and add it to the row_num_2, 
# exchanging row_num_2 of the matrix M in the result
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    print(M_new)
    return M_new
# R2 = R2 - R1
A_new = AddRows(A_new, 0, 1, -1)


A_new = AddRows(A_new, 0, 2, 1)


A_new = AddRows(A_new, 0, 3, -1)


A_new = MultiplyByNonZero(A_new, 1, 1/2.5)


A_new = AddRows(A_new, 1, 2, -1.5)
A_new = AddRows(A_new, 1, 3, .5)


A_new = MultiplyByNonZero(A_new, 2, 1/3.4)

A_new = AddRows(A_new, 2, 3, -1.2)


[[ 2. -1.  1.  1.  6.]
 [ 1.  2. -1. -1.  3.]
 [-1.  2.  2.  2. 14.]
 [ 1. -1.  2.  1.  8.]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 1.   2.  -1.  -1.   3. ]
 [-1.   2.   2.   2.  14. ]
 [ 1.  -1.   2.   1.   8. ]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 0.   2.5 -1.5 -1.5  0. ]
 [-1.   2.   2.   2.  14. ]
 [ 1.  -1.   2.   1.   8. ]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 0.   2.5 -1.5 -1.5  0. ]
 [ 0.   1.5  2.5  2.5 17. ]
 [ 1.  -1.   2.   1.   8. ]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 0.   2.5 -1.5 -1.5  0. ]
 [ 0.   1.5  2.5  2.5 17. ]
 [ 0.  -0.5  1.5  0.5  5. ]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 0.   1.  -0.6 -0.6  0. ]
 [ 0.   1.5  2.5  2.5 17. ]
 [ 0.  -0.5  1.5  0.5  5. ]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 0.   1.  -0.6 -0.6  0. ]
 [ 0.   0.   3.4  3.4 17. ]
 [ 0.  -0.5  1.5  0.5  5. ]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 0.   1.  -0.6 -0.6  0. ]
 [ 0.   0.   3.4  3.4 17. ]
 [ 0.   0.   1.2  0.2  5. ]]
[[ 1.  -0.5  0.5  0.5  3. ]
 [ 0.   1.  -0.6 -0.6  0. ]
 [ 0.   0.   1.   1.   5. ]
 [ 0.   0.   1.2  0.2  5. ]]
[[ 

In [124]:
x4 = 1
x3 = 5 - 5 -x4
x2 = 0 +.6*x3+.6*x4
x1 = 3 +.5*x2 -.5*x3 -.5*x4

print(x1, x2, x3, x4)


3.0 0.0 -1 1


In [123]:
A_new[2,2]

np.float64(1.0000000000000002)

array([[ 1. , -0.5,  0.5,  0.5,  3. ],
       [ 0. ,  2.5, -1.5, -1.5,  0. ],
       [ 0. ,  1.5,  2.5,  2.5, 17. ],
       [ 1. , -1. ,  2. ,  1. ,  8. ]])

array([[ 1. , -0.5,  0.5,  0.5,  3. ],
       [ 0. ,  2.5, -1.5, -1.5,  0. ],
       [ 0. ,  1.5,  2.5,  2.5, 17. ],
       [ 0. , -0.5,  1.5,  0.5,  5. ]])

array([[ 1. , -0.5,  0.5,  0.5,  3. ],
       [ 0. ,  1. , -0.6, -0.6,  0. ],
       [ 0. ,  1.5,  2.5,  2.5, 17. ],
       [ 0. , -0.5,  1.5,  0.5,  5. ]])

array([[ 1. , -0.5,  0.5,  0.5,  3. ],
       [ 0. ,  1. , -0.6, -0.6,  0. ],
       [ 0. ,  0.5,  3.1,  3.1, 17. ],
       [ 0. , -0.5,  1.5,  0.5,  5. ]])